/**
 * Jira MCP service plugin.
 *
 * Per-user Atlassian Cloud Jira access. Auth is paste-creds (workspace
 * URL + email + API token); the API token is generated by the user at
 * https://id.atlassian.com/manage-profile/security/api-tokens.
 *
 * Atlassian Cloud uses HTTP Basic with `<email>:<api_token>`. The MCP
 * fetches both pieces from the cap-token bridge and pre-bakes the basic
 * auth header per process.
 */
import {
  registerManagedMcpService,
  type ManagedCredentialStatus,
} from "../managed-mcp";
import {
  setJiraCredential,
  readJiraStatus,
  deleteJiraCredential,
} from "@/lib/credentials/jira";

registerManagedMcpService({
  service: "jira",
  label: "Atlassian Jira",
  emoji: "🟦",
  prefix: "jira-",
  capabilityScope: "jira.token",
  entryEnvVar: "FLATCLAW_JIRA_MCP_ENTRY",
  description:
    "Per-user Atlassian Jira access — issues, projects, transitions, comments, worklogs. Auth via your Atlassian API token (generated at id.atlassian.com → API tokens), paired with your account email.",
  // Tool inventory (mirrors mcp/jira/src/tools/*). Surfaced as per-user Tool
  // Access toggles → native tools.deny. Runs in verbose/full mode (real tools
  // exposed), so per-tool denial takes effect.
  toolGroups: [
    {
      id: "issues",
      label: "Issues & search",
      description: "Read, search, create, update, transition issues + links.",
      tools: [
        "get_issue", "search_issues", "create_issue", "update_issue",
        "transition_issue", "list_transitions", "assign_issue",
        "approximate_issue_count", "get_issue_type_fields",
        "create_issue_link", "list_issue_links", "list_link_types",
      ],
    },
    {
      id: "comments",
      label: "Comments & worklogs",
      description: "Issue comments and worklog entries.",
      tools: ["add_comment", "list_comments", "add_worklog"],
    },
    {
      id: "projects",
      label: "Projects",
      description: "Project metadata, components, issue types, statuses, versions.",
      tools: [
        "get_project", "list_projects", "list_project_components",
        "list_project_issue_types", "list_project_statuses", "list_project_versions",
      ],
    },
    {
      id: "users",
      label: "Users",
      description: "User lookups.",
      tools: ["myself", "search_users", "list_assignable_users", "lookup_user_by_email"],
    },
    {
      id: "attachments",
      label: "Attachments",
      description: "Issue attachment read/write.",
      tools: [
        "attach_file_to_issue", "list_issue_attachments", "download_attachment",
        "delete_attachment", "get_attachment_metadata",
      ],
    },
    {
      id: "raw",
      label: "Raw API",
      description: "Escape hatch: arbitrary authenticated Jira REST call.",
      tools: ["jira_request"],
    },
  ],
  buildExtraEnv: () => {
    // Same lane-defaults pattern as cpanel/caldav/google. Prod (128k+
    // context) gets the full ~25 tools; dev (32k) gets ~12 core tools.
    // Full toolset everywhere — A100 dev has KV room.
    const toolset = process.env.FLATCLAW_JIRA_MCP_TOOLSET ?? "full";
    const mode = process.env.FLATCLAW_JIRA_MCP_MODE ?? "verbose";
    return { JIRA_MCP_TOOLSET: toolset, JIRA_MCP_MODE: mode };
  },
  auth: {
    kind: "form",
    fields: [
      {
        name: "workspaceUrl",
        label: "Workspace URL",
        placeholder: "https://kirktechsolutions.atlassian.net",
        type: "url",
        required: true,
        help: "Your Atlassian workspace URL — the part before /jira. e.g. https://yourcompany.atlassian.net.",
      },
      {
        name: "email",
        label: "Atlassian account email",
        placeholder: "you@yourcompany.com",
        type: "text",
        required: true,
        help: "The email tied to the Atlassian account that generated the API token. Used as the Basic-auth username.",
      },
      {
        name: "apiToken",
        label: "API token",
        placeholder: "ATATT3xFfGF0…",
        type: "secret",
        required: true,
        help: "Generate at https://id.atlassian.com/manage-profile/security/api-tokens. Long-lived until you revoke it.",
      },
    ],
  },
  async setCredential(userId, payload) {
    const workspaceUrl = String(payload.workspaceUrl ?? "").trim();
    const email = String(payload.email ?? "").trim();
    const apiToken = String(payload.apiToken ?? "").trim();
    if (!workspaceUrl || !email || !apiToken) {
      throw new Error("workspaceUrl, email, and apiToken are required");
    }
    if (!/^https?:\/\//i.test(workspaceUrl)) {
      throw new Error("workspaceUrl must include https://");
    }
    await setJiraCredential(userId, { workspaceUrl, email, apiToken });
  },
  async readStatus(userId): Promise<ManagedCredentialStatus> {
    const s = await readJiraStatus(userId);
    return {
      connected: s.connected,
      identity: s.email
        ? `${s.email} @ ${s.workspaceUrl ?? "?"}`
        : null,
      updatedAt: s.updatedAt ? s.updatedAt.getTime() : null,
      lastUsedAt: s.lastUsedAt ? s.lastUsedAt.getTime() : null,
      meta: { workspaceUrl: s.workspaceUrl },
    };
  },
  async deleteCredential(userId) {
    await deleteJiraCredential(userId);
  },
});
